### ISSUE TITLE
Improved data source handling for database connections

### ISSUE THREAD

**Issue by GuusLieben** [GuusLieben/Hartshorn#766]
### Related problem

Currently the way connections are configured in repositories is decent at best. Connections need to be provided manually, or are automatically inferred from the global connection. E.g.:
https://github.com/GuusLieben/Hartshorn/blob/bc6cf2b73698837455aff22e51c90f84cdeb8438/hartshorn-data/src/test/java/org/dockbox/hartshorn/data/SqlServiceTest.java#L139-L141

### Requested feature

Add the option to define a custom data source through a annotation-driven solution. This should default to the default connection if not configured, or use the defined connection.
```java
@Service
@DataSource("users")
public interface UserRepository extends JpaRepository<User, Long> { ... }
```
This should allow the default configuration source to be used, so application properties can be used to configure the data sources. In YAML this should be similar to:
```yaml
hartshorn:
  data:
    sources:
      data-source-name:
        dialect: org.hibernate.dialect.YourDataBaseDialect # Any valid Dialect extending org.hibernate.dialect.Dialect
        url: jdbc:database-type://localhost:0000/databaseName # Any valid connection string
        driver: com.yourdatabase.jdbc.Driver # Any valid driver extending java.sql.Driver
        username: root # Optional, can also be in connection string if preferred
        password: root # Optional, can also be in connection string if preferred
```
These values can be accessed through the `PropertyHolder` binding, but should not depend strictly on that (though a default implementation is allowed and expected to do so). Likely a separate connection bundle is an appropriate solution, so it can be overwritten by third parties if required.

Connections should contain all the information required, so the currently existing `Remote` implementations should be removed.
